---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1024
    natdnshostresolver1: "on"
  network:
    - ["forwarded_port", {guest: 5601, host: 5601, auto_correct: true}]
    - ["forwarded_port", {guest: 9200, host: 9200, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.38

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[elk-chef::server]
      - recipe[elk-chef::client]
    attributes:
      dev_mode: true
